// <auto-generated />
using System;
using Ejercicio1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ejercicio1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ejercicio1.Models.Dispositivo", b =>
                {
                    b.Property<int>("DispositivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DispositivoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DispositivoId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Dispositivos");

                    b.HasData(
                        new
                        {
                            DispositivoId = 1,
                            Nombre = "Laptop HP"
                        },
                        new
                        {
                            DispositivoId = 2,
                            Nombre = "Monitor Samsung"
                        },
                        new
                        {
                            DispositivoId = 3,
                            Nombre = "Teclado Logitech"
                        },
                        new
                        {
                            DispositivoId = 4,
                            Nombre = "Mouse Razer"
                        },
                        new
                        {
                            DispositivoId = 5,
                            Nombre = "Tablet iPad"
                        });
                });

            modelBuilder.Entity("Ejercicio1.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"));

                    b.Property<int>("DispositivoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("DATEADD(DAY, 1, GETDATE())");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ReservaId");

                    b.HasIndex("DispositivoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas");

                    b.HasData(
                        new
                        {
                            ReservaId = 1,
                            DispositivoId = 1,
                            FechaFin = new DateTime(2025, 12, 21, 18, 16, 52, 986, DateTimeKind.Local).AddTicks(3795),
                            FechaInicio = new DateTime(2025, 12, 14, 18, 16, 52, 986, DateTimeKind.Local).AddTicks(3737),
                            UsuarioId = 1
                        },
                        new
                        {
                            ReservaId = 2,
                            DispositivoId = 2,
                            FechaFin = new DateTime(2025, 12, 13, 18, 16, 52, 986, DateTimeKind.Local).AddTicks(3798),
                            FechaInicio = new DateTime(2025, 12, 6, 18, 16, 52, 986, DateTimeKind.Local).AddTicks(3797),
                            UsuarioId = 2
                        },
                        new
                        {
                            ReservaId = 3,
                            DispositivoId = 3,
                            FechaFin = new DateTime(2025, 12, 23, 18, 16, 52, 986, DateTimeKind.Local).AddTicks(3800),
                            FechaInicio = new DateTime(2025, 12, 19, 18, 16, 52, 986, DateTimeKind.Local).AddTicks(3799),
                            UsuarioId = 3
                        },
                        new
                        {
                            ReservaId = 4,
                            DispositivoId = 4,
                            FechaFin = new DateTime(2025, 12, 18, 18, 16, 52, 986, DateTimeKind.Local).AddTicks(3803),
                            FechaInicio = new DateTime(2025, 12, 15, 18, 16, 52, 986, DateTimeKind.Local).AddTicks(3802),
                            UsuarioId = 4
                        });
                });

            modelBuilder.Entity("Ejercicio1.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            NombreCompleto = "Juan Garcia"
                        },
                        new
                        {
                            UsuarioId = 2,
                            NombreCompleto = "Maria Lopez"
                        },
                        new
                        {
                            UsuarioId = 3,
                            NombreCompleto = "Pedro Martinez"
                        },
                        new
                        {
                            UsuarioId = 4,
                            NombreCompleto = "Ana Rodriguez"
                        });
                });

            modelBuilder.Entity("Ejercicio1.Models.Reserva", b =>
                {
                    b.HasOne("Ejercicio1.Models.Dispositivo", "Dispositivo")
                        .WithMany("Reservas")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ejercicio1.Models.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispositivo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Ejercicio1.Models.Dispositivo", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Ejercicio1.Models.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
