// <auto-generated />
using System;
using Ejercicio2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ejercicio2_Librerias.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ejercicio2.Models.Orden", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("OrdenId");

                    b.ToTable("Ordenes");

                    b.HasData(
                        new
                        {
                            OrdenId = 1,
                            Fecha = new DateTime(2025, 12, 16, 0, 55, 24, 523, DateTimeKind.Local).AddTicks(3965)
                        },
                        new
                        {
                            OrdenId = 2,
                            Fecha = new DateTime(2025, 12, 17, 0, 55, 24, 523, DateTimeKind.Local).AddTicks(3973)
                        });
                });

            modelBuilder.Entity("Ejercicio2.Models.OrdenDetalle", b =>
                {
                    b.Property<int>("OrdenDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenDetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("OrdenDetalleId");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("OrdenesDetalle");

                    b.HasData(
                        new
                        {
                            OrdenDetalleId = 1,
                            Cantidad = 2,
                            OrdenId = 1,
                            ProductoId = 1
                        },
                        new
                        {
                            OrdenDetalleId = 2,
                            Cantidad = 5,
                            OrdenId = 1,
                            ProductoId = 3
                        },
                        new
                        {
                            OrdenDetalleId = 3,
                            Cantidad = 1,
                            OrdenId = 2,
                            ProductoId = 2
                        });
                });

            modelBuilder.Entity("Ejercicio2.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadDisponible = 10,
                            Nombre = "Laptop",
                            Precio = 1500m
                        },
                        new
                        {
                            Id = 2,
                            CantidadDisponible = 25,
                            Nombre = "Monitor",
                            Precio = 300m
                        },
                        new
                        {
                            Id = 3,
                            CantidadDisponible = 50,
                            Nombre = "Teclado",
                            Precio = 25m
                        });
                });

            modelBuilder.Entity("Ejercicio2.Models.OrdenDetalle", b =>
                {
                    b.HasOne("Ejercicio2.Models.Orden", "Orden")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ejercicio2.Models.Producto", "Producto")
                        .WithMany("OrdenesDetalle")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Orden");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Ejercicio2.Models.Orden", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Ejercicio2.Models.Producto", b =>
                {
                    b.Navigation("OrdenesDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
